app:
  myport: ${PORT:0}
server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://EUREKA-SERVER:8761/eureka
spring:
  application:
    name: pedido-service
  data:
    mongodb:
      uri: mongodb://MONGO-SERVER:27017/test